{
 "title": "MyMetrics",
 "tags": [
  "Grafana",
  "Prometheus",
  "Endpints"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "helloworld-Contador",
   "type": "timeseries",
   "description": "http://localhost:8080/helloworld",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "targets": [
    { "expr": "invocaciones_hello_total", "legendFormat": "counter" }
   ]
  },
  {
   "title": "max_data_size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 0 },
   "targets": [
    { "expr": "jvm_gc_max_data_size_bytes" }
   ]
  },
  {
   "title": "Uso de CPU del sistema",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 7 },
   "targets": [
    { "expr": "system_cpu_usage" }
   ]
  },
  {
   "title": "Start time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 7 },
   "targets": [
    { "expr": "process_start_time_seconds" }
   ]
  }
 ]
}